// Code generated by "stringer -type=Arch"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[I686-0]
	_ = x[X86_64-1]
	_ = x[Arm64-2]
}

const _Arch_name = "I686X86_64Arm64"

var _Arch_index = [...]uint8{0, 4, 10, 15}

func (i Arch) String() string {
	if i < 0 || i >= Arch(len(_Arch_index)-1) {
		return "Arch(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Arch_name[_Arch_index[i]:_Arch_index[i+1]]
}
