name: Preview

on:
  workflow_dispatch:
  push:
    tags:
      - 'v\d+\.\d+\.\d+'

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          go build -o ridgo cmd/ridgoCli/main.go
          PATH+=:$(pwd)

      - name: Generate preview
        uses: charmbracelet/vhs-action@v2
        with:
          path: .github/preview.tape

      - name: Move preview
        run: mv preview.gif .github/preview.gif

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: Update preview image'
          title: 'chore: Update preview image'
          branch: preview-$(date +%s)
